name: online-market
version: '0.1.0.0'
synopsis: online market daily statistics
description: Applying the online library to daily market returns.
category: statistics
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day
license: BSD3
github: tonyday567/online-dev
default-extensions:
- NoImplicitPrelude
- UnicodeSyntax
- BangPatterns
- BinaryLiterals
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DisambiguateRecordFields
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTSyntax
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadComprehensions
- MultiParamTypeClasses
- MultiWayIf
- NegativeLiterals
- OverloadedStrings
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- RankNTypes
- RecordWildCards
- RecursiveDo
- ScopedTypeVariables
- TupleSections
- TypeFamilies
- TypeOperators
ghc-options:
- -funbox-strict-fields
- -fforce-recomp
- -threaded
- -rtsopts
- -with-rtsopts=-N
dependencies:
- base >=4.7 && <5
- ListLike
- ad
- attoparsec
- binary
- bytestring
- cassava
- chart-unit
- data-default
- generic-lens-labels
- diagrams-lib
- diagrams-svg
- foldl
- formatting
- numhask
- numhask-range
- numhask-histogram
- online
- optparse-generic
- protolude
- reflection
- tdigest
- vector
- lens
- time
- text
executables:
  online-market-examples:
    main: examples.hs
    source-dirs: ./examples
