resolver: lts-15.6

packages:
  - .

extra-deps:
  - readme-lhs-0.5.0
  - palette-0.3.0.2
  - backprop-0.2.6.3
  - vinyl-0.12.1
  - lucid-svg-0.7.1
  - javascript-bridge-0.2.0
  - online-0.4.0.0
  - chart-svg-0.0.1
  - box-0.2.0
  - numhask-prelude-0.3.3
  - numhask-space-0.3.1
  - web-rep-0.3.1
  - text-format-0.3.2
  - interpolatedstring-perl6-1.0.2
  - monad-bayes-0.1.1.0
  - online-csv-0.0.1

allow-newer: true
