resolver: lts-14.13

packages:
  - .
  - ../chart-svg
  - ../online/online
  - ../numhask-space
  - ../pmlb
  - ../web-rep
  - ../readme-lhs

extra-deps:
  - lucid-svg-0.7.1
  - javascript-bridge-0.2.0
  - box-0.1.0
  - streaming-utils-0.2.0.0
  - json-stream-0.4.2.4

allow-newer: true
