resolver: lts-14.13

packages:
  - .
  - ../chart-svg
  - ../online/online
  - ../numhask-space

extra-deps:
  - lucid-svg-0.7.1
  - javascript-bridge-0.2.0
  # - numhask-space-0.2.0
  - web-rep-0.1.2
  - box-0.0.1.5

allow-newer: true
