resolver: lts-15.6

packages:
  - .

extra-deps:
  - readme-lhs-0.5.0
  - palette-0.3.0.2
  - backprop-0.2.6.3
  - vinyl-0.12.1
  - lucid-svg-0.7.1
  - javascript-bridge-0.2.0
  - streaming-utils-0.2.0.0
  - json-stream-0.4.2.4
  - online-0.4.0.0
  - chart-svg-0.0.1
  - box-0.2.0
  - numhask-space-0.3.1
  - web-rep-0.3.1
  - text-format-0.3.2
  - interpolatedstring-perl6-1.0.2
  - git: https://github.com/adscib/monad-bayes
    commit: fb87bf039bab35dcc82de8ccf8963a7a576af355
  - git: https://github.com/tonyday567/pmlb
    commit: 5b1d7fe0a6ed6451aea844f74d543e67cdc2eb11

allow-newer: true
