resolver: nightly-2020-06-25

packages:
  - .

extra-deps:
  - backprop-0.2.6.4
  - box-0.5.0
  - box-csv-0.0.1
  - box-socket-0.0.1
  - chart-svg-0.1.1
  - hslua-1.1.2
  - jira-wiki-markup-1.3.2
  - monad-bayes-0.1.1.0
  - numhask-0.6.0
  - numhask-array-0.7.0
  - numhask-space-0.5.0
  - online-0.6.0
  - pandoc-2.10
  - readme-lhs-0.7.0
  - vinyl-0.13.0
  - web-rep-0.6.0

allow-newer: true
