resolver: lts-15.6

packages:
  - .

extra-deps:
  - readme-lhs-0.5.0
  - backprop-0.2.6.3
  - vinyl-0.12.1
  - lucid-svg-0.7.1
  - javascript-bridge-0.2.0
  - online-0.4.0.0
  # - chart-svg-0.0.1
  - git: https://github.com/tonyday567/chart-svg
    commit: 436afe6d9f49782200d5d851fc8a36e330ddef8e
  - box-0.2.0
  - numhask-prelude-0.3.3
  - numhask-space-0.3.1
  # - web-rep-0.3.1
  - git: https://github.com/tonyday567/web-rep
    commit: 0863a2974af30ece6cb46fb8a1198cb9b053c5e2
  - text-format-0.3.2
  - interpolatedstring-perl6-1.0.2
  - monad-bayes-0.1.1.0
  - online-csv-0.0.1
  # - numhask-array-0.5.1
  - git: https://github.com/tonyday567/numhask-array
    commit: 08ca2b79d3d97c662dffbe4960183378e156b25a
allow-newer: true
