resolver: lts-7.19

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
    git: https://github.com/tonyday567/tower.git
    commit: ff36e3028c84d45329b6dc928150f317e598ee1c
  extra-dep: true
- location:
    git: https://github.com/tonyday567/chart-unit.git
    commit: 44ab3937808f0210036c0cb2b054af1ca5933c9e
  extra-dep: true
- location:
    git: https://github.com/tonyday567/online.git
    commit: e56d10c903a928b98b1b6ec4156f725da1f2b521
  extra-dep: true
- location:
    git: https://github.com/futurice/haskell-tdigest
    commit: 7b16d730b84b1fca2f97dfa3862d5781856d19e9
  extra-dep: true
