resolver: nightly-2018-01-17

packages:
  - '.'

extra-deps:
  - git: https://github.com/kcsongor/generic-lens.git
    commit: 876ad15282e2ea5e5d77e3eae4c4a2bba77bd81a
  - git: https://github.com/tonyday567/generic-lens-labels.git
    commit: 268482be078e543c1f8fef33ae8ceabc7a201f8b
  - git: https://github.com/tonyday567/numhask-histogram.git
    commit: 31041224eef1a56d132dbeae6c65c477881b82f9
  - git: https://github.com/tonyday567/chart-unit.git
    commit: 81faffbeeb68614f6fa7be99f9a7bd38be2bb8b3
  - git: https://github.com/tonyday567/online.git
    commit: 06b0f5633c000207b84efa87f333cae934767ce3
