resolver: lts-7.19

# Local packages, usually specified by relative directory name
packages:
- '.'
- '../chart-unit'
- '../online'
# - location:
#     git: https://github.com/tonyday567/chart-unit.git
#     commit: b8485c83fda7b6768010053f7faa66e7f37d4fb1
#   extra-dep: true
- location:
    git: https://github.com/tonyday567/tower.git
    commit: ff36e3028c84d45329b6dc928150f317e598ee1c
  extra-dep: true
